/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GameWordleRouteImport } from './routes/GameWordle'
import { Route as GamePokemonRouteImport } from './routes/GamePokemon'
import { Route as GamePkmnRouteImport } from './routes/GamePkmn'
import { Route as Game2048RouteImport } from './routes/Game2048'
import { Route as IndexRouteImport } from './routes/index'

const GameWordleRoute = GameWordleRouteImport.update({
  id: '/GameWordle',
  path: '/GameWordle',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePokemonRoute = GamePokemonRouteImport.update({
  id: '/GamePokemon',
  path: '/GamePokemon',
  getParentRoute: () => rootRouteImport,
} as any)
const GamePkmnRoute = GamePkmnRouteImport.update({
  id: '/GamePkmn',
  path: '/GamePkmn',
  getParentRoute: () => rootRouteImport,
} as any)
const Game2048Route = Game2048RouteImport.update({
  id: '/Game2048',
  path: '/Game2048',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Game2048': typeof Game2048Route
  '/GamePkmn': typeof GamePkmnRoute
  '/GamePokemon': typeof GamePokemonRoute
  '/GameWordle': typeof GameWordleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Game2048': typeof Game2048Route
  '/GamePkmn': typeof GamePkmnRoute
  '/GamePokemon': typeof GamePokemonRoute
  '/GameWordle': typeof GameWordleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Game2048': typeof Game2048Route
  '/GamePkmn': typeof GamePkmnRoute
  '/GamePokemon': typeof GamePokemonRoute
  '/GameWordle': typeof GameWordleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/Game2048' | '/GamePkmn' | '/GamePokemon' | '/GameWordle'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Game2048' | '/GamePkmn' | '/GamePokemon' | '/GameWordle'
  id:
    | '__root__'
    | '/'
    | '/Game2048'
    | '/GamePkmn'
    | '/GamePokemon'
    | '/GameWordle'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Game2048Route: typeof Game2048Route
  GamePkmnRoute: typeof GamePkmnRoute
  GamePokemonRoute: typeof GamePokemonRoute
  GameWordleRoute: typeof GameWordleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/GameWordle': {
      id: '/GameWordle'
      path: '/GameWordle'
      fullPath: '/GameWordle'
      preLoaderRoute: typeof GameWordleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/GamePokemon': {
      id: '/GamePokemon'
      path: '/GamePokemon'
      fullPath: '/GamePokemon'
      preLoaderRoute: typeof GamePokemonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/GamePkmn': {
      id: '/GamePkmn'
      path: '/GamePkmn'
      fullPath: '/GamePkmn'
      preLoaderRoute: typeof GamePkmnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Game2048': {
      id: '/Game2048'
      path: '/Game2048'
      fullPath: '/Game2048'
      preLoaderRoute: typeof Game2048RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Game2048Route: Game2048Route,
  GamePkmnRoute: GamePkmnRoute,
  GamePokemonRoute: GamePokemonRoute,
  GameWordleRoute: GameWordleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
