/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PokeHangmanRouteImport } from './routes/PokeHangman'
import { Route as NotWordleRouteImport } from './routes/NotWordle'
import { Route as IndexRouteImport } from './routes/index'

const PokeHangmanRoute = PokeHangmanRouteImport.update({
  id: '/PokeHangman',
  path: '/PokeHangman',
  getParentRoute: () => rootRouteImport,
} as any)
const NotWordleRoute = NotWordleRouteImport.update({
  id: '/NotWordle',
  path: '/NotWordle',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/NotWordle': typeof NotWordleRoute
  '/PokeHangman': typeof PokeHangmanRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/NotWordle': typeof NotWordleRoute
  '/PokeHangman': typeof PokeHangmanRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/NotWordle': typeof NotWordleRoute
  '/PokeHangman': typeof PokeHangmanRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/NotWordle' | '/PokeHangman'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/NotWordle' | '/PokeHangman'
  id: '__root__' | '/' | '/NotWordle' | '/PokeHangman'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NotWordleRoute: typeof NotWordleRoute
  PokeHangmanRoute: typeof PokeHangmanRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/PokeHangman': {
      id: '/PokeHangman'
      path: '/PokeHangman'
      fullPath: '/PokeHangman'
      preLoaderRoute: typeof PokeHangmanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/NotWordle': {
      id: '/NotWordle'
      path: '/NotWordle'
      fullPath: '/NotWordle'
      preLoaderRoute: typeof NotWordleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NotWordleRoute: NotWordleRoute,
  PokeHangmanRoute: PokeHangmanRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
